"""add project provenance

Revision ID: 4938b1e500be
Revises: 28055bd91b11
Create Date: 2026-10-01 21:13:01.322077
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4938b1e500be'
down_revision: str | None = '28055bd91b11'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_sources',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'chunk_id')
    )
    op.create_index(op.f('ix_project_sources_chunk_id'), 'project_sources', ['chunk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_sources_chunk_id'), table_name='project_sources')
    op.drop_table('project_sources')
    # ### end Alembic commands ###