"""add tasks and commitments

Revision ID: 60e7b2d27d11
Revises: bed55f5e8630
Create Date: 2026-09-30 22:46:59.717380
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '60e7b2d27d11'
down_revision: str | None = 'bed55f5e8630'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commitments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('deadline_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='open', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commitments_project_id'), 'commitments', ['project_id'], unique=False)
    op.create_index(op.f('ix_commitments_user_id'), 'commitments', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('commitment_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='open', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commitment_id'], ['commitments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_commitment_id'), 'tasks', ['commitment_id'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('commitment_sources',
    sa.Column('commitment_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['commitment_id'], ['commitments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('commitment_id', 'chunk_id')
    )
    op.create_index(op.f('ix_commitment_sources_chunk_id'), 'commitment_sources', ['chunk_id'], unique=False)
    op.create_table('task_sources',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'chunk_id')
    )
    op.create_index(op.f('ix_task_sources_chunk_id'), 'task_sources', ['chunk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_sources_chunk_id'), table_name='task_sources')
    op.drop_table('task_sources')
    op.drop_index(op.f('ix_commitment_sources_chunk_id'), table_name='commitment_sources')
    op.drop_table('commitment_sources')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_commitment_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_commitments_user_id'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_project_id'), table_name='commitments')
    op.drop_table('commitments')
    # ### end Alembic commands ###