"""add model runs

Revision ID: 7603b99ab102
Revises: e04fc5e1be03
Create Date: 2026-10-02 14:48:06.341949
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7603b99ab102'
down_revision: str | None = 'e04fc5e1be03'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_runs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('finish_reason', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error_type', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_runs_operation'), 'model_runs', ['operation'], unique=False)
    op.create_index(op.f('ix_model_runs_started_at'), 'model_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_model_runs_status'), 'model_runs', ['status'], unique=False)
    op.create_index(op.f('ix_model_runs_user_id'), 'model_runs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_runs_user_id'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_status'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_started_at'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_operation'), table_name='model_runs')
    op.drop_table('model_runs')
    # ### end Alembic commands ###