"""add user authentication subject

Revision ID: b6eb92b7fe05
Revises: 7603b99ab102
Create Date: 2026-10-02 18:13:10.938461
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b6eb92b7fe05'
down_revision: str | None = '7603b99ab102'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_subject', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_users_auth_subject'), 'users', ['auth_subject'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_auth_subject'), table_name='users')
    op.drop_column('users', 'auth_subject')
    # ### end Alembic commands ###