"""add embeddings to document chunks

Revision ID: b9fc260a9146
Revises: 42c8b76a8a03
Create Date: 2026-09-26 19:03:18.739178
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


revision: str = 'b9fc260a9146'
down_revision: str | None = '42c8b76a8a03'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('document_chunks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    op.add_column('document_chunks', sa.Column('embedding', Vector(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'embedding')
    # ### end Alembic commands ###