"""add risks and risk sources

Revision ID: e04fc5e1be03
Revises: 704138fb6254
Create Date: 2026-10-01 21:46:12.831916
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e04fc5e1be03'
down_revision: str | None = '704138fb6254'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_user_id'), 'risks', ['user_id'], unique=False)
    op.create_table('risk_sources',
    sa.Column('risk_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('risk_id', 'chunk_id')
    )
    op.create_index(op.f('ix_risk_sources_chunk_id'), 'risk_sources', ['chunk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_sources_chunk_id'), table_name='risk_sources')
    op.drop_table('risk_sources')
    op.drop_index(op.f('ix_risks_user_id'), table_name='risks')
    op.drop_table('risks')
    # ### end Alembic commands ###